### ISSUE TITLE
Access token could not be read

### ISSUE THREAD

**Issue by AresDev** [stephen-mitchell/PebHub#5]
I've installed the app but got this message "Access token could not be read", what I need to do to have the access token, I've entered github from safari but that didn't work.

Thanks!

**Comment by stephen-mitchell** [comment]
GitHub have changed their Settings pages. The URL you need to visit to generate a personal access token is now [https://github.com/settings/tokens](https://github.com/settings/tokens). Its best to do this from a browser on your phone so that you can copy and paste the token. Click "Generate new token", enter a description and select the "repo" scope if you want to see notifications for private repositories. Copy the generated token into the text box in the application settings and click "Submit". You'll need to restart the PebHub app on your watch for the change to take effect.

I've just followed these instructions successfully using a Pebble Time and the latest version of the Pebble Time Android app. If they don't work for you, please let me know and I'll look into this in more detail.

**Comment by stephen-mitchell** [comment]
The correct link has now been added to the config page.
